services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build: ./App_BDJ-back
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./App_BDJ-back/.env
    environment:
      - DB_HOST=db 
    depends_on:
      - db

  frontend:
    build: ../App_BDJ
    ports:
      - "8081:8081"
      - "19000:19000"
    volumes:
      - ../App_BDJ:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=127.0.0.1
      - EXPO_PACKAGER_PROXY_URL=http://127.0.0.1:8081
    stdin_open: true
    tty: true